import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import matter from 'gray-matter';
import GithubSlugger from 'github-slugger';
import { toString } from 'mdast-util-to-string';
import readingTime from 'reading-time';
import rehypeHighlight from 'rehype-highlight';
import rehypeSlug from 'rehype-slug';
import rehypeStringify from 'rehype-stringify';
import remarkFrontmatter from 'remark-frontmatter';
import remarkGfm from 'remark-gfm';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';
import { visit } from 'unist-util-visit';
import type { HeadingLink, GeneratedPage, GeneratedPost, GeneratedProject, ProjectStatus } from '../src/app/blog/models';

const rootDir = process.cwd();
const postsDirectory = path.join(rootDir, 'content', 'posts');
const pagesDirectory = path.join(rootDir, 'content', 'pages');
const projectsDirectory = path.join(rootDir, 'content', 'projects');
const outputDirectory = path.join(rootDir, 'src', 'app', 'blog', 'generated');
const outputFile = path.join(outputDirectory, 'content.generated.ts');
const publicDirectory = path.join(rootDir, 'public');
const rssOutputFile = path.join(publicDirectory, 'rss.xml');
const sitemapOutputFile = path.join(publicDirectory, 'sitemap.xml');
const robotsOutputFile = path.join(publicDirectory, 'robots.txt');
const siteTitle = 'Ben Halverson';
const siteDescription = 'Developer writing on Angular, TypeScript, performance, Cloudflare, and pragmatic web architecture.';
const siteUrl = 'https://benhalverson.com';

const optionalPostFields = new Set(['updatedAt', 'coverImage', 'canonicalUrl', 'featured']);
const optionalProjectFields = new Set(['updatedAt', 'repoUrl', 'demoUrl', 'docsUrl', 'featured']);
const requiredPostFields = ['title', 'slug', 'description', 'publishedAt', 'tags', 'draft'];
const requiredProjectFields = ['title', 'slug', 'description', 'status', 'startedAt', 'tags', 'draft'];
const requiredPageFields = ['title', 'slug', 'description'];

await mkdir(outputDirectory, { recursive: true });
await mkdir(publicDirectory, { recursive: true });

const generatedPosts = await collectContent(postsDirectory, parsePostFile);
const generatedPages = await collectContent(pagesDirectory, parsePageFile);
const generatedProjects = await collectContent(projectsDirectory, parseProjectFile);

generatedPosts.sort((left, right) => right.publishedAt.localeCompare(left.publishedAt));
generatedProjects.sort((left, right) => (right.updatedAt ?? right.startedAt).localeCompare(left.updatedAt ?? left.startedAt));

const fileContents = `/* auto-generated by tools/generate-content.ts; do not edit directly */\nimport type { GeneratedPage, GeneratedPost, GeneratedProject } from '../models';\n\nexport const generatedPosts: GeneratedPost[] = ${JSON.stringify(generatedPosts, null, 2)};\n\nexport const generatedPages: GeneratedPage[] = ${JSON.stringify(generatedPages, null, 2)};\n\nexport const generatedProjects: GeneratedProject[] = ${JSON.stringify(generatedProjects, null, 2)};\n`;

await writeFile(outputFile, fileContents, 'utf8');
await writeFile(rssOutputFile, buildRssFeed(generatedPosts), 'utf8');
await writeFile(sitemapOutputFile, buildSitemap(generatedPosts, generatedProjects, generatedPages), 'utf8');
await writeFile(robotsOutputFile, buildRobotsTxt(), 'utf8');

async function collectContent<T>(directory: string, parser: (fileName: string, source: string) => Promise<T>): Promise<T[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const content: T[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue;
    }

    const source = await readFile(path.join(directory, entry.name), 'utf8');
    content.push(await parser(entry.name, source));
  }

  return content;
}

async function parsePostFile(fileName: string, source: string): Promise<GeneratedPost> {
  const { content, data } = matter(source);

  assertFields(fileName, data, requiredPostFields, optionalPostFields);

  const rendered = await renderMarkdown(content);
  const stats = readingTime(content);

  return {
    title: expectString(data.title, `${fileName} title`),
    slug: expectString(data.slug, `${fileName} slug`),
    description: expectString(data.description, `${fileName} description`),
    publishedAt: expectDateString(data.publishedAt, `${fileName} publishedAt`),
    updatedAt: optionalDateString(data.updatedAt, `${fileName} updatedAt`),
    tags: expectStringArray(data.tags, `${fileName} tags`),
    draft: expectBoolean(data.draft, `${fileName} draft`),
    coverImage: optionalString(data.coverImage, `${fileName} coverImage`),
    canonicalUrl: optionalString(data.canonicalUrl, `${fileName} canonicalUrl`),
    featured: typeof data.featured === 'boolean' ? data.featured : false,
    readingTime: {
      text: stats.text,
      minutes: Number(stats.minutes.toFixed(2)),
      words: stats.words,
    },
    headings: rendered.headings,
    html: rendered.html,
  };
}

async function parsePageFile(fileName: string, source: string): Promise<GeneratedPage> {
  const { content, data } = matter(source);

  assertFields(fileName, data, requiredPageFields, new Set());
  const rendered = await renderMarkdown(content);

  return {
    title: expectString(data.title, `${fileName} title`),
    slug: expectString(data.slug, `${fileName} slug`),
    description: expectString(data.description, `${fileName} description`),
    headings: rendered.headings,
    html: rendered.html,
  };
}

async function parseProjectFile(fileName: string, source: string): Promise<GeneratedProject> {
  const { content, data } = matter(source);

  assertFields(fileName, data as Record<string, unknown>, requiredProjectFields, optionalProjectFields);
  const rendered = await renderMarkdown(content);

  return {
    title: expectString(data.title, `${fileName} title`),
    slug: expectString(data.slug, `${fileName} slug`),
    description: expectString(data.description, `${fileName} description`),
    status: expectProjectStatus(data.status, `${fileName} status`),
    startedAt: expectDateString(data.startedAt, `${fileName} startedAt`),
    updatedAt: optionalDateString(data.updatedAt, `${fileName} updatedAt`),
    tags: expectStringArray(data.tags, `${fileName} tags`),
    draft: expectBoolean(data.draft, `${fileName} draft`),
    featured: typeof data.featured === 'boolean' ? data.featured : false,
    repoUrl: optionalString(data.repoUrl, `${fileName} repoUrl`),
    demoUrl: optionalString(data.demoUrl, `${fileName} demoUrl`),
    docsUrl: optionalString(data.docsUrl, `${fileName} docsUrl`),
    headings: rendered.headings,
    html: rendered.html,
  };
}

async function renderMarkdown(markdown: string): Promise<{ headings: HeadingLink[]; html: string }> {
  const headings: HeadingLink[] = [];
  const slugger = new GithubSlugger();

  const file = await unified()
    .use(remarkParse)
    .use(remarkFrontmatter, ['yaml'])
    .use(remarkGfm)
    .use(function collectHeadings() {
      return (tree: unknown) => {
        visit(tree, 'heading', (node) => {
          if (node.depth < 2 || node.depth > 3) {
            return;
          }

          const text = toString(node).trim();

          if (!text) {
            return;
          }

          headings.push({
            depth: node.depth,
            id: slugger.slug(text),
            text,
          });
        });
      };
    })
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeHighlight)
    .use(rehypeStringify)
    .process(markdown);

  return {
    headings,
    html: String(file),
  };
}

function assertFields(
  fileName: string,
  data: Record<string, unknown>,
  requiredFields: string[],
  optionalFields: Set<string>,
): void {
  for (const field of requiredFields) {
    if (!(field in data)) {
      throw new Error(`Missing required field "${field}" in ${fileName}`);
    }
  }

  for (const field of Object.keys(data)) {
    if (!requiredFields.includes(field) && !optionalFields.has(field)) {
      throw new Error(`Unexpected field "${field}" in ${fileName}`);
    }
  }
}

function expectString(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${label} must be a non-empty string`);
  }

  return value;
}

function optionalString(value: unknown, label: string): string | undefined {
  if (typeof value === 'undefined') {
    return undefined;
  }

  return expectString(value, label);
}

function expectDateString(value: unknown, label: string): string {
  if (typeof value === 'string' && value.trim().length > 0) {
    return value;
  }

  if (value instanceof Date && !Number.isNaN(value.valueOf())) {
    return value.toISOString().slice(0, 10);
  }

  throw new Error(`${label} must be a non-empty string or valid date`);
}

function optionalDateString(value: unknown, label: string): string | undefined {
  if (typeof value === 'undefined') {
    return undefined;
  }

  return expectDateString(value, label);
}

function expectBoolean(value: unknown, label: string): boolean {
  if (typeof value !== 'boolean') {
    throw new Error(`${label} must be a boolean`);
  }

  return value;
}

function expectStringArray(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string' || item.trim().length === 0)) {
    throw new Error(`${label} must be an array of non-empty strings`);
  }

  return value;
}

function expectProjectStatus(value: unknown, label: string): ProjectStatus {
  if (value === 'active' || value === 'paused' || value === 'planning' || value === 'shipping') {
    return value;
  }

  throw new Error(`${label} must be one of: active, paused, planning, shipping`);
}

function buildRssFeed(posts: GeneratedPost[]): string {
  const publishedPosts = posts.filter((post) => !post.draft);
  const latestPublishedDate = publishedPosts[0]?.updatedAt ?? publishedPosts[0]?.publishedAt ?? new Date().toISOString().slice(0, 10);
  const items = publishedPosts
    .map((post) => {
      const postUrl = post.canonicalUrl ?? `${siteUrl}/posts/${post.slug}`;
      const pubDate = toRfc822Date(post.publishedAt);
      const categories = post.tags.map((tag) => `      <category>${escapeXml(tag)}</category>`).join('\n');

      return [
        '    <item>',
        `      <title>${escapeXml(post.title)}</title>`,
        `      <link>${escapeXml(postUrl)}</link>`,
        `      <guid isPermaLink="true">${escapeXml(postUrl)}</guid>`,
        `      <description>${escapeXml(post.description)}</description>`,
        `      <pubDate>${pubDate}</pubDate>`,
        categories,
        `      <content:encoded><![CDATA[${post.html}]]></content:encoded>`,
        '    </item>',
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0"',
    '  xmlns:atom="http://www.w3.org/2005/Atom"',
    '  xmlns:content="http://purl.org/rss/1.0/modules/content/"',
    '>',
    '  <channel>',
    `    <title>${escapeXml(siteTitle)}</title>`,
    `    <link>${siteUrl}</link>`,
    `    <description>${escapeXml(siteDescription)}</description>`,
    '    <language>en-us</language>',
    `    <lastBuildDate>${toRfc822Date(latestPublishedDate)}</lastBuildDate>`,
    `    <atom:link href="${siteUrl}/rss.xml" rel="self" type="application/rss+xml" />`,
    items,
    '  </channel>',
    '</rss>',
    '',
  ].join('\n');
}

function buildSitemap(posts: GeneratedPost[], projects: GeneratedProject[], pages: GeneratedPage[]): string {
  const routes = new Map<string, string>();
  const publishedPosts = posts.filter((post) => !post.draft);
  const publishedProjects = projects.filter((project) => !project.draft);
  const tags = [...new Set(publishedPosts.flatMap((post) => post.tags.map((tag) => tag.toLowerCase())))].sort();

  routes.set('/', latestDate([
    ...publishedPosts.map((post) => post.updatedAt ?? post.publishedAt),
    ...publishedProjects.map((project) => project.updatedAt ?? project.startedAt),
  ]));
  routes.set('/posts', publishedPosts[0]?.updatedAt ?? publishedPosts[0]?.publishedAt ?? currentIsoDate());
  routes.set('/projects', publishedProjects[0]?.updatedAt ?? publishedProjects[0]?.startedAt ?? currentIsoDate());

  for (const page of pages) {
    routes.set(`/${page.slug}`, currentIsoDate());
  }

  for (const post of publishedPosts) {
    routes.set(`/posts/${post.slug}`, post.updatedAt ?? post.publishedAt);
  }

  for (const project of publishedProjects) {
    routes.set(`/projects/${project.slug}`, project.updatedAt ?? project.startedAt);
  }

  for (const tag of tags) {
    const matchingPosts = publishedPosts.filter((post) => post.tags.some((postTag) => postTag.toLowerCase() === tag));
    routes.set(`/tags/${encodeURIComponent(tag)}`, latestDate(matchingPosts.map((post) => post.updatedAt ?? post.publishedAt)));
  }

  const entries = [...routes.entries()]
    .map(([route, lastModified]) => {
      return [
        '  <url>',
        `    <loc>${escapeXml(`${siteUrl}${route}`)}</loc>`,
        `    <lastmod>${lastModified}</lastmod>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    '</urlset>',
    '',
  ].join('\n');
}

function buildRobotsTxt(): string {
  return [
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${siteUrl}/sitemap.xml`,
    '',
  ].join('\n');
}

function latestDate(values: string[]): string {
  if (values.length === 0) {
    return currentIsoDate();
  }

  return [...values].sort((left, right) => right.localeCompare(left))[0];
}

function currentIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function toRfc822Date(value: string): string {
  return new Date(`${value}T00:00:00Z`).toUTCString();
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}
